DELETE http://localhost:3001/api/blogs/65d6ab01100fa8f848db9516
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NWQ2OTljYTRlMzYwMzE5NDgwMmUzMGQiLCJpYXQiOjE3MDg1Njg0NDh9._7nigZiRdhc3UQ6lBXBsJRiNrHQv8QyCadDajC1-KIE
Content-Type: application/json
